#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
HF Daily Papers Generator
生成 Markdown 和 PDF 格式的论文推荐报告
"""

import os
import re
import urllib.request
import json
from datetime import datetime
from fpdf import FPDF

# Optional proxy: set `HF_DAILY_PAPERS_PROXY` (e.g. http://127.0.0.1:7897) if you need it.
_proxy = os.environ.get('HF_DAILY_PAPERS_PROXY')
if _proxy:
    os.environ['HTTP_PROXY'] = _proxy
    os.environ['HTTPS_PROXY'] = _proxy

def fetch_papers():
    """获取 HF Daily Papers"""
    print("📥 获取 HF Daily Papers...")
    
    # 获取页面
    req = urllib.request.Request("https://huggingface.co/papers", headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req, timeout=30) as r:
        html = r.read().decode()
    
    # 提取论文 ID
    paper_ids = list(set(re.findall(r'href="/papers/([0-9]+\.[0-9]+)"', html)))[:30]
    
    # 获取论文详情
    papers = []
    for i, pid in enumerate(paper_ids):
        try:
            url = f"https://huggingface.co/api/papers/{pid}"
            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(req, timeout=10) as r:
                data = json.loads(r.read().decode())
                papers.append({
                    'pid': pid,
                    'title': data.get('title', 'N/A')[:100],
                    'upvotes': data.get('upvotes', 0),
                    'summary': data.get('summary', '')[:500].lower()
                })
        except Exception as e:
            continue
        
        if (i+1) % 10 == 0:
            print(f"  已处理 {i+1}/{len(paper_ids)}...")
    
    # 按 upvotes 排序
    papers.sort(key=lambda x: x['upvotes'], reverse=True)
    return papers

def filter_papers(papers):
    """筛选论文"""
    gen_kw = ['diffusion', 'video', 'image', 'gan', 'generation', 'generative', 'synthesis', 'text-to', 'autoregressive']
    eff_kw = ['efficient', 'attention', 'quant', 'sparse', 'compress', 'memory', 'compute', 'optimization']
    
    gen_papers = [p for p in papers if any(kw in p['title'].lower() or kw in p['summary'] for kw in gen_kw)]
    eff_papers = [p for p in papers if any(kw in p['title'].lower() or kw in p['summary'] for kw in eff_kw)]
    
    return gen_papers, eff_papers

def generate_markdown(gen_papers, eff_papers, output_dir, timestamp):
    """生成 Markdown 文件"""
    date_str = datetime.now().strftime('%Y-%m-%d')
    md_file = os.path.join(output_dir, f"{date_str}.md")
    
    md_content = f"""# Hugging Face Daily Papers 推荐

**生成时间**: {timestamp}

---

## 🎨 生成领域推荐 ({len(gen_papers)} 篇)

"""
    
    for i, p in enumerate(gen_papers[:15], 1):
        md_content += f"""### [{p['pid']}](https://huggingface.co/papers/{p['pid']}) - {p['title']}

**Upvotes**: {p['upvotes']}

"""
    
    md_content += f"""

## ⚡ Efficient 高效化领域推荐 ({len(eff_papers)} 篇)

"""
    
    for i, p in enumerate(eff_papers[:15], 1):
        md_content += f"""### [{p['pid']}](https://huggingface.co/papers/{p['pid']}) - {p['title']}

**Upvotes**: {p['upvotes']}

"""
    
    md_content += """---
*Generated by OpenClaw HF Daily Papers Skill*
"""
    
    with open(md_file, 'w', encoding='utf-8') as f:
        f.write(md_content)
    
    print(f"✅ Markdown: {md_file}")
    return md_file

def generate_pdf(gen_papers, eff_papers, output_dir, timestamp):
    """生成 PDF 文件"""
    date_str = datetime.now().strftime('%Y-%m-%d')
    pdf_file = os.path.join(output_dir, f"{date_str}.pdf")
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # 标题
    pdf.set_font('Arial', 'B', 18)
    pdf.cell(0, 10, 'Hugging Face Daily Papers', ln=True, align='C')
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, 'Recommendation Report', ln=True, align='C')
    pdf.ln(5)
    pdf.set_font('Arial', '', 10)
    pdf.cell(0, 8, f'Generated: {timestamp}', ln=True)
    pdf.ln(5)
    
    # 生成领域
    pdf.set_font('Arial', 'B', 14)
    pdf.set_fill_color(230, 240, 255)
    pdf.cell(0, 10, f'Generation Domain ({len(gen_papers)} papers)', ln=True, fill=True)
    pdf.ln(3)
    pdf.set_font('Arial', '', 9)
    
    for i, p in enumerate(gen_papers[:15], 1):
        pdf.set_font('Arial', 'B', 9)
        title = re.sub(r'[^\x00-\x7F]+', '', p['title'])[:70]
        pdf.cell(0, 6, f"{i}. [{p['pid']}] {title}", ln=True)
        pdf.set_font('Arial', 'I', 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"   Upvotes: {p['upvotes']}", ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)
    
    pdf.ln(5)
    
    # Efficient 领域
    pdf.set_font('Arial', 'B', 14)
    pdf.set_fill_color(240, 250, 230)
    pdf.cell(0, 10, f'Efficient Domain ({len(eff_papers)} papers)', ln=True, fill=True)
    pdf.ln(3)
    pdf.set_font('Arial', '', 9)
    
    for i, p in enumerate(eff_papers[:15], 1):
        pdf.set_font('Arial', 'B', 9)
        title = re.sub(r'[^\x00-\x7F]+', '', p['title'])[:70]
        pdf.cell(0, 6, f"{i}. [{p['pid']}] {title}", ln=True)
        pdf.set_font('Arial', 'I', 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"   Upvotes: {p['upvotes']}", ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)
    
    pdf.set_y(-20)
    pdf.set_font('Arial', 'I', 8)
    pdf.cell(0, 10, 'Generated by OpenClaw HF Daily Papers Skill', align='C')
    
    pdf.output(pdf_file)
    print(f"✅ PDF: {pdf_file}")
    return pdf_file

def main():
    import sys
    
    generate_pdf_flag = '--pdf' in sys.argv
    
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    output_dir = os.path.dirname(os.path.abspath(__file__)) + "/recommendations"
    os.makedirs(output_dir, exist_ok=True)
    
    # 获取并筛选论文
    papers = fetch_papers()
    gen_papers, eff_papers = filter_papers(papers)
    
    print(f"\n📊 Total: {len(papers)} papers | Generation: {len(gen_papers)} | Efficient: {len(eff_papers)}")
    
    # 生成 Markdown
    generate_markdown(gen_papers, eff_papers, output_dir, timestamp)
    
    # 生成 PDF（如果需要）
    if generate_pdf_flag:
        try:
            from fpdf import FPDF
            generate_pdf(gen_papers, eff_papers, output_dir, timestamp)
        except ImportError:
            print("⚠️ fpdf not installed. Run: pip3 install fpdf")

if __name__ == '__main__':
    main()
